apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  labels:
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: prometheus
    name: prometheus-server
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
  
